#!/bin/bash
container_name=dast_app
html_src=html_src
# Continuous Integration
docker build . --file build/Dockerfile-prd  -t "${container_name}_image"
# wait for copy and stop container
docker run --rm -d --name $container_name "${container_name}_image" sleep 30
docker cp $container_name:/app $html_src
# Continuous Delivery
aws s3 sync --delete $html_src s3://lttrung-dast-bucket/public
# Clean cache
aws cloudfront  create-invalidation --distribution-id E21U7PULRELFOQ --paths "/*"