name: Backend API 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install-aws-cli-action
      uses: unfor19/install-aws-cli-action@v1.0.3
      with:
        role-to-assume: arn:aws:iam::128294669461:role/GithubAction
        aws-region: ap-southeast-1
    - name: Deployment
      run: aws ssm send-command --document-name "deploy-api" --document-version "\$LATEST" --targets '[{"Key":"InstanceIds","Values":["i-0313a365b5195670e"]}]' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --region ap-southeast-1
