name: Backend API 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#   schedule:
#     - cron: '0 17 * * 0'
    
permissions:
 id-token: write
 contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::128294669461:role/GithubAction
        aws-region: ap-southeast-1
    
    - name: Deployment
      run: aws ssm send-command --document-name "deploy-api" --document-version "\$LATEST" --targets '[{"Key":"InstanceIds","Values":["i-0313a365b5195670e"]}]' --timeout-seconds 600 --max-concurrency "50" --max-errors "0"
    
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      if: always()
      env:
        SLACK_CHANNEL: C04176JK2JU
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: API Deployment
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
