name: Node.js CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'src/reactapp/src'
    steps:
    - uses: actions/checkout@v3
    - name: Build dependencies
      run: yarn
    - name: Build html
      run: yarn build
    - name: Check source
      run: ls -alh build
