name: Node.js CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'src/reactapp/src'
    steps:
    - uses: actions/checkout@v3
    - run: |
      yarn
      yarn build
      ls -alh build
